const API="http://127.0.0.1:8000";const ESTADOS=["sano","caries","restaurado","ausente","realizado","indicado"];const ETIQUETAS={sano:"Sano",caries:"Caries",restaurado:"Restaurado",ausente:"Ausente",realizado:"Tratamiento realizado",indicado:"Tratamiento indicado"};let pacienteId=null,datos={},pieza=null,estadoTemporal="sano";
function toast(m,t="success"){const x=document.getElementById("toast");if(!x)return;x.textContent=m;x.className=`toast show ${t}`;setTimeout(()=>x.classList.remove("show"),3000)}function qp(){return new URLSearchParams(location.search).get("paciente")||localStorage.getItem("paciente_odontograma_id")}
async function api(url,opt={}){const r=await fetch(API+url,{headers:{"Content-Type":"application/json","X-User-Role":"odontologo"},...opt});if(!r.ok){const e=await r.json().catch(()=>({}));throw Error(e.detail||`Error ${r.status}`)}return r.json()}
function tipoDiente(n){const u=n%10;return [1,2].includes(u)?"incisivo":[3].includes(u)?"canino":[4,5].includes(u)?"premolar":"molar"}
function pathDiente(tipo){return {incisivo:"M21 3 C14 3 10 8 10 16 L11 39 C11 47 14 51 21 51 C28 51 31 47 31 39 L32 16 C32 8 28 3 21 3 Z",canino:"M21 3 C15 4 11 10 12 17 L15 45 C16 50 18 52 21 52 C24 52 26 50 27 45 L30 17 C31 10 27 4 21 3 Z",premolar:"M21 4 C14 4 8 9 8 17 C8 25 11 29 10 38 C10 47 14 51 21 51 C28 51 32 47 32 38 C31 29 34 25 34 17 C34 9 28 4 21 4 Z",molar:"M13 5 C7 6 4 12 5 19 L8 42 C9 49 14 52 21 51 C28 52 33 49 34 42 L37 19 C38 12 35 6 29 5 L25 8 L21 5 L17 8 Z"}[tipo]}
function svgDiente(n){const tipo=tipoDiente(n);return `<svg class="tooth-svg" viewBox="0 0 42 56" aria-label="Diente ${n}"><path d="${pathDiente(tipo)}"></path></svg>`}
function construir(){const grupos={q1:[18,17,16,15,14,13,12,11],q2:[21,22,23,24,25,26,27,28],q3:[31,32,33,34,35,36,37,38],q4:[48,47,46,45,44,43,42,41]};Object.entries(grupos).forEach(([id,piezas])=>{const el=document.getElementById(id);if(el)el.innerHTML=piezas.map(diente).join("")});document.querySelectorAll(".tooth").forEach(x=>x.addEventListener("click",()=>seleccionar(Number(x.dataset.diente))));actualizarEstadisticas()}
function diente(n){const d=datos[n]||{estado:"sano",observacion:""};return `<button type="button" class="tooth ${d.estado||"sano"}" data-diente="${n}" title="Diente ${n} - ${ETIQUETAS[d.estado]||"Sano"}">${svgDiente(n)}<span class="tooth-number">${n}</span></button>`}
function actualizarEstadisticas(){const c={sano:0,caries:0,restaurado:0,ausente:0,realizado:0,indicado:0};const piezas=[18,17,16,15,14,13,12,11,21,22,23,24,25,26,27,28,48,47,46,45,44,43,42,41,31,32,33,34,35,36,37,38];for(const n of piezas){const estado=datos[n]?.estado||"sano";if(c[estado]!==undefined)c[estado]++;}const total=32,body=document.getElementById("statsBody");body.innerHTML=ESTADOS.map(e=>{const pct=(c[e]/total*100);return `<tr><td><span class="badge-dot ${e}"></span>${ETIQUETAS[e]}</td><td><strong>${c[e]}</strong></td><td>${pct.toFixed(1)}%</td><td><div class="stat-bar"><span style="width:${pct}%"></span></div></td></tr>`}).join("");const afectados=total-c.sano;document.getElementById("statsNote").textContent=`De 32 piezas permanentes, ${c.sano} están registradas como sanas y ${afectados} presentan algún hallazgo o tratamiento.`}
function seleccionar(n){pieza=n;const d=datos[n]||{estado:"sano",observacion:""};estadoTemporal=d.estado||"sano";document.getElementById("piezaSeleccionada").textContent=`Pieza ${n}`;document.getElementById("editorTitulo").textContent=`Diente ${n}`;document.getElementById("observacion").value=d.observacion||"";document.querySelectorAll(".tooth").forEach(x=>x.classList.toggle("selected",Number(x.dataset.diente)===n));document.querySelectorAll("#estados button").forEach(x=>x.classList.toggle("active",x.dataset.estado===estadoTemporal))}
function aplicar(){if(!pieza){toast("Selecciona primero una pieza dental","warning");return}datos[pieza]={estado:estadoTemporal,observacion:document.getElementById("observacion").value.trim()};construir();seleccionar(pieza);toast(`Pieza ${pieza} actualizada`)}
async function guardar(){if(!pacienteId)return;const b=document.getElementById("btnGuardar");b.disabled=true;try{await api(`/odontogramas/paciente/${pacienteId}`,{method:"PUT",body:JSON.stringify({id_paciente:Number(pacienteId),dientes:datos})});toast("Odontograma guardado correctamente")}catch(e){toast(e.message,"error")}finally{b.disabled=false}}
async function iniciar(){pacienteId=qp();if(!pacienteId){location.href="panel_odontologo.html";return}try{const p=await api(`/pacientes/${pacienteId}`);document.getElementById("pacienteNombre").textContent=`${p.nombre} ${p.apellido} · Documento ${p.documento}`;const o=await api(`/odontogramas/paciente/${pacienteId}`);datos=o.dientes||{};construir()}catch(e){toast(e.message,"error");construir()}}
document.addEventListener("DOMContentLoaded",()=>{const u=JSON.parse(localStorage.getItem("usuario_actual")||"null");if(!u){location.href="login.html";return}if(String(u.rol||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()!=="odontologo"){location.href="panel.html";return}document.querySelectorAll("#estados button").forEach(b=>b.onclick=()=>{estadoTemporal=b.dataset.estado;document.querySelectorAll("#estados button").forEach(x=>x.classList.toggle("active",x===b))});document.getElementById("btnAplicar").onclick=aplicar;document.getElementById("btnGuardar").onclick=guardar;iniciar()});
