const API = "http://127.0.0.1:8000";
let pacientes = [];
function toast(msg,tipo="success"){const t=document.getElementById("toast");if(!t)return;t.textContent=msg;t.className=`toast show ${tipo}`;setTimeout(()=>t.classList.remove("show"),3000)}
function usuarioActual(){try{return JSON.parse(localStorage.getItem("usuario_actual")||"null")}catch{return null}}
function normalizarRol(rol){return String(rol||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim()}
function esOdontologo(){return normalizarRol(usuarioActual()?.rol)==="odontologo"}
async function api(path){const u=usuarioActual();const r=await fetch(`${API}${path}`,{headers:{"X-User-Role":u?.rol||"","X-User-Id":String(u?.id_usuario||"")}});if(!r.ok){const e=await r.json().catch(()=>({}));throw new Error(e.detail||`Error ${r.status}`)}return r.json()}
function iniciales(p){return `${(p.nombre||"")[0]||""}${(p.apellido||"")[0]||""}`.toUpperCase()}
function escapar(v){return String(v??"").replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderPacientes(lista){const grid=document.getElementById("pacientesGrid");if(!lista.length){grid.innerHTML='<div class="pacientes-vacio"><span class="material-symbols-outlined" style="font-size:42px">person_search</span><p>No hay pacientes que coincidan con la búsqueda.</p></div>';return}grid.innerHTML=lista.map(p=>`<article class="paciente-card"><div class="paciente-card-header"><div class="paciente-avatar">${escapar(iniciales(p))}</div><div><h3>${escapar(p.nombre)} ${escapar(p.apellido)}</h3><small>Paciente #${p.id_paciente}</small></div></div><div class="paciente-datos"><div class="paciente-dato"><span class="material-symbols-outlined">badge</span><span>${escapar(p.documento)}</span></div><div class="paciente-dato"><span class="material-symbols-outlined">mail</span><span>${escapar(p.correo||"Sin correo")}</span></div><div class="paciente-dato"><span class="material-symbols-outlined">call</span><span>${escapar(p.telefono||"Sin teléfono")}</span></div><div class="paciente-dato"><span class="material-symbols-outlined">health_and_safety</span><span>${escapar(p.eps||"EPS no registrada")}</span></div></div><div class="paciente-acciones"><button class="btn-clinico" onclick="abrirHistoria(${p.id_paciente})"><span class="material-symbols-outlined">clinical_notes</span> Historia clínica</button><button class="btn-odonto" onclick="abrirOdontograma(${p.id_paciente})"><span class="material-symbols-outlined">dentistry</span> Odontograma</button></div></article>`).join("")}
function filtrar(){const q=document.getElementById("buscarPaciente").value.trim().toLowerCase();renderPacientes(pacientes.filter(p=>`${p.nombre} ${p.apellido} ${p.documento} ${p.correo||""}`.toLowerCase().includes(q)))}
async function cargarPacientes(){try{const r=await api('/pacientes');pacientes=Array.isArray(r)?r.filter(p=>p&&p.id_paciente):[];document.getElementById('cntPacientes').textContent=pacientes.length;renderPacientes(pacientes);try{const citas=await api('/citas');document.getElementById('cntCitas').textContent=Array.isArray(citas)?citas.length:0}catch{document.getElementById('cntCitas').textContent='—'}}catch(e){document.getElementById('pacientesGrid').innerHTML=`<div class="pacientes-vacio">❌ ${escapar(e.message)}</div>`;toast('No se pudieron cargar los pacientes','error')}}
function abrirHistoria(id){localStorage.setItem('paciente_clinico_id',String(id));window.location.href=`historia_clinica.html?paciente=${id}`}
function abrirOdontograma(id){localStorage.setItem('paciente_odontograma_id',String(id));window.location.href=`odontograma.html?paciente=${id}`}
window.cargarPacientes=cargarPacientes;window.abrirHistoria=abrirHistoria;window.abrirOdontograma=abrirOdontograma;
document.addEventListener('DOMContentLoaded',()=>{const u=usuarioActual();if(!u){location.href='login.html';return}if(!esOdontologo()){const rol=normalizarRol(u.rol);location.href=rol==='paciente'?'panel_cliente.html':'panel.html';return}document.getElementById('odontologoSaludo').textContent=`Sesión: ${u.correo}`;document.getElementById('buscarPaciente').addEventListener('input',filtrar);cargarPacientes()});
