import type { Appointment as LegacyAppointment, PatientRecord, Pago, Factura, Proveedor, Tratamiento, User as LegacyUser } from '../types';
import type { Appointment, Patient, Payment, Invoice, Supplier, Treatment, User } from './unifiedDomain';

export const adaptUser = (u: LegacyUser): User => ({ id: u.id, tenantId: u.tenantId, email: u.email, name: u.name, role: u.role, active: true });
export const adaptPatient = (p: PatientRecord): Patient => ({ id: p.id, tenantId: p.tenantId, firstName: p.nombre, lastName: p.apellido, email: p.email, phone: p.phone, birthDate: p.birthDate || p.fecha_nacimiento, notes: [p.alergias, p.notes].filter(Boolean).join(' | ') || undefined, active: true, documentType: 'CC', documentNumber: p.documento });
export const adaptTreatment = (t: Tratamiento): Treatment => ({ id: t.id_tratamiento, tenantId: t.tenantId, name: t.nombre, description: t.descripcion, price: t.costo, status: 'planned' });
export const adaptAppointment = (a: LegacyAppointment): Appointment => ({ id: a.id, tenantId: a.tenantId, patientId: a.patientId, dentistId: a.dentistId, officeId: a.id_consultorio, startAt: `${a.date}T${a.time}:00`, endAt: new Date(new Date(`${a.date}T${a.time}:00`).getTime() + a.durationMinutes * 60000).toISOString(), status: a.status, reason: a.treatment, notes: a.notes });
export const adaptPayment = (p: Pago, tenantId = 'tenant-1'): Payment => ({ id: p.id_pago, tenantId, appointmentId: p.id_cita, amount: p.monto, method: p.metodo_pago === 'Efectivo' ? 'cash' : p.metodo_pago.includes('Tarjeta') ? 'card' : p.metodo_pago.includes('Transferencia') ? 'transfer' : 'other', status: p.estado_pago === 'Completado' ? 'paid' : p.estado_pago === 'Pendiente' ? 'pending' : 'cancelled', paidAt: p.fecha_pago });
export const adaptInvoice = (f: Factura, tenantId = 'tenant-1'): Invoice => ({ id: f.id_factura, tenantId, number: f.id_factura, subtotal: f.subtotal, tax: f.impuesto, total: f.total, status: 'issued', issuedAt: f.fecha_emision });
export const adaptSupplier = (p: Proveedor): Supplier => ({ id: p.id, tenantId: p.tenantId, name: p.empresa, email: p.correo, phone: p.telefono, active: p.estado_convenio === 'Vigente' });
