import type { Appointment as LegacyAppointment, PatientRecord, Pago, Factura, Proveedor, Tratamiento, User as LegacyUser } from '../types';
import type { Appointment, Patient, Payment, Invoice, Supplier, Treatment, User } from './unifiedDomain';

export const adaptUser = (u: LegacyUser): User => ({ id: u.id, tenantId: u.tenantId || 'tenant-1', email: u.email, name: u.name, role: u.role, phone: u.phone, documento: u.documento, avatarUrl: u.avatarUrl, createdAt: u.createdAt });
export const adaptPatient = (p: PatientRecord): Patient => ({ id: p.id, tenantId: p.tenantId, firstName: p.nombre, lastName: p.apellido, fullName: p.name, email: p.email, phone: p.phone, document: p.documento, birthDate: p.birthDate || p.fecha_nacimiento, gender: p.genero, address: p.direccion, eps: p.eps, allergies: p.alergias, notes: p.notes, odontogram: p.odontogram, createdAt: p.historiaDetallada?.fecha_actualizacion || new Date().toISOString() });
export const adaptTreatment = (t: Tratamiento): Treatment => ({ id: t.id_tratamiento, tenantId: t.tenantId, name: t.nombre, description: t.descripcion, price: t.costo, estimatedDuration: t.duracion_estimada });
export const adaptAppointment = (a: LegacyAppointment): Appointment => ({ id: a.id, tenantId: a.tenantId, dentistId: a.dentistId, dentistName: a.dentistName, patientId: a.patientId, patientName: a.patientName, patientEmail: a.patientEmail, patientPhone: a.patientPhone, officeId: a.id_consultorio, officeName: a.consultorioNombre, date: a.date, time: a.time, durationMinutes: a.durationMinutes, status: a.status, treatment: a.treatment, treatmentIds: a.tratamientosIds || [], notes: a.notes, price: a.price, createdAt: a.createdAt });
export const adaptPayment = (p: Pago): Payment => ({ id: p.id_pago, tenantId: 'tenant-1', appointmentId: p.id_cita, date: p.fecha_pago, amount: p.monto, method: p.metodo_pago, status: p.estado_pago, reference: p.referencia });
export const adaptInvoice = (f: Factura, tenantId = 'tenant-1'): Invoice => ({ id: f.id_factura, tenantId, paymentId: f.id_pago, issueDate: f.fecha_emision, subtotal: f.subtotal, tax: f.impuesto, total: f.total });
export const adaptSupplier = (p: Proveedor): Supplier => ({ id: p.id, tenantId: p.tenantId || 'tenant-1', company: p.empresa, contactName: p.contacto_asesor, phone: p.telefono, supply: p.suministro, status: p.estado_convenio, email: p.correo, address: p.direccion, notes: p.notas, registeredAt: p.fecha_registro });
