-- OdontoSoft - sincronización de la base PostgreSQL antigua con el backend actual
--
-- Origen esperado: dump legacy de ProyectoApi / OdontoSoft.
-- IMPORTANTE: ejecutar sobre una COPIA/backup de la base antes de producción.
-- Esta migración NO crea tablas automáticamente desde SQLAlchemy; sincroniza
-- explícitamente el esquema existente y conserva los datos que son compatibles.

BEGIN;

-- ============================================================
-- 1. USUARIO
-- ============================================================

ALTER TABLE public.usuario
    ADD COLUMN IF NOT EXISTS fecha_registro timestamp without time zone;

ALTER TABLE public.usuario
    ADD COLUMN IF NOT EXISTS ultimo_acceso timestamp without time zone;

ALTER TABLE public.usuario
    ALTER COLUMN correo TYPE varchar(100);

ALTER TABLE public.usuario
    ALTER COLUMN contrasena TYPE varchar(255);

-- La aplicación autentica con hash en usuario.contrasena.
-- No se elimina paciente.contrasena_plano porque el modelo actual todavía
-- lo conserva por compatibilidad histórica; no debe utilizarse como secreto.

UPDATE public.usuario
SET estado = 'Activo'
WHERE estado IS NULL OR btrim(estado) = '';

ALTER TABLE public.usuario
    ALTER COLUMN estado SET DEFAULT 'Activo';

ALTER TABLE public.usuario
    ALTER COLUMN estado SET NOT NULL;

ALTER TABLE public.usuario
    ALTER COLUMN correo TYPE varchar(100);

-- ============================================================
-- 2. ODONTÓLOGO: ampliar longitudes del modelo actual
-- ============================================================

ALTER TABLE public.odontologo
    ALTER COLUMN registro_profesional TYPE varchar(100);

ALTER TABLE public.odontologo
    ALTER COLUMN horario TYPE varchar(200);

-- ============================================================
-- 3. PROVEEDOR: ampliar empresa a varchar(200)
-- ============================================================

ALTER TABLE public.proveedor
    ALTER COLUMN empresa TYPE varchar(200);

-- ============================================================
-- 4. CITA: estado por defecto compatible con el backend
-- ============================================================

UPDATE public.cita
SET estado = 'Pendiente'
WHERE estado IS NULL OR estado = 'En Espera';

ALTER TABLE public.cita
    ALTER COLUMN estado SET DEFAULT 'Pendiente';

-- ============================================================
-- 5. SERVICIO: el backend usa paciente_id, no id_paciente
-- ============================================================

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'servicio'
          AND column_name = 'id_paciente'
    )
    AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'servicio'
          AND column_name = 'paciente_id'
    ) THEN
        ALTER TABLE public.servicio RENAME COLUMN id_paciente TO paciente_id;
    END IF;
END $$;

-- El esquema legacy hacía que tratamiento dependiera de una sola cita.
-- El backend actual modela cita <-> tratamiento como relación N:N mediante
-- cita_tratamiento, por lo que se preservan primero esos vínculos y luego se
-- elimina la dependencia antigua.

INSERT INTO public.cita_tratamiento (id_cita, id_tratamiento)
SELECT t.id_cita, t.id_tratamiento
FROM public.tratamiento AS t
WHERE t.id_cita IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM public.cita_tratamiento AS ct
      WHERE ct.id_cita = t.id_cita
        AND ct.id_tratamiento = t.id_tratamiento
  );

ALTER TABLE public.tratamiento
    DROP CONSTRAINT IF EXISTS fk_tratamiento_cita;

ALTER TABLE public.tratamiento
    DROP COLUMN IF EXISTS id_cita;

-- El servicio actual no depende directamente de tratamiento.id; usa los
-- campos de presentación definidos por el backend.
ALTER TABLE public.servicio
    DROP CONSTRAINT IF EXISTS servicio_id_tratamiento_fkey;

ALTER TABLE public.servicio
    DROP COLUMN IF EXISTS id_tratamiento;

-- ============================================================
-- 6. PASSWORD RESET: tabla requerida por PasswordResetToken
-- ============================================================

CREATE TABLE IF NOT EXISTS public.password_reset_token (
    id_token integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token varchar(255) NOT NULL UNIQUE,
    id_usuario integer NOT NULL,
    fecha_creacion timestamp without time zone NOT NULL,
    fecha_expiracion timestamp without time zone NOT NULL,
    usado boolean NOT NULL DEFAULT false,
    CONSTRAINT password_reset_token_usuario_fkey
        FOREIGN KEY (id_usuario)
        REFERENCES public.usuario(id_usuario)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_password_reset_token_id_token
    ON public.password_reset_token (id_token);

CREATE INDEX IF NOT EXISTS ix_password_reset_token_token
    ON public.password_reset_token (token);

CREATE INDEX IF NOT EXISTS ix_password_reset_token_id_usuario
    ON public.password_reset_token (id_usuario);

-- ============================================================
-- 7. ÍNDICES DE FK utilizados frecuentemente por el backend
-- ============================================================

CREATE INDEX IF NOT EXISTS ix_cita_id_paciente
    ON public.cita (id_paciente);

CREATE INDEX IF NOT EXISTS ix_cita_id_odontologo
    ON public.cita (id_odontologo);

CREATE INDEX IF NOT EXISTS ix_cita_id_consultorio
    ON public.cita (id_consultorio);

CREATE INDEX IF NOT EXISTS ix_historia_clinica_id_paciente
    ON public.historia_clinica (id_paciente);

CREATE INDEX IF NOT EXISTS ix_odontograma_id_paciente
    ON public.odontograma (id_paciente);

CREATE INDEX IF NOT EXISTS ix_historia_clinica_detallada_id_paciente
    ON public.historia_clinica_detallada (id_paciente);

CREATE INDEX IF NOT EXISTS ix_pago_id_cita
    ON public.pago (id_cita);

CREATE INDEX IF NOT EXISTS ix_recordatorio_id_cita
    ON public.recordatorio (id_cita);

CREATE INDEX IF NOT EXISTS ix_servicio_paciente_id
    ON public.servicio (paciente_id);

-- ============================================================
-- 8. Secuencias existentes: evitar colisiones después de importar datos
-- ============================================================

SELECT setval(
    pg_get_serial_sequence('public.usuario', 'id_usuario'),
    GREATEST(COALESCE((SELECT MAX(id_usuario) FROM public.usuario), 0), 1),
    COALESCE((SELECT MAX(id_usuario) FROM public.usuario), 0) > 0
);

SELECT setval(
    pg_get_serial_sequence('public.paciente', 'id_paciente'),
    GREATEST(COALESCE((SELECT MAX(id_paciente) FROM public.paciente), 0), 1),
    COALESCE((SELECT MAX(id_paciente) FROM public.paciente), 0) > 0
);

SELECT setval(
    pg_get_serial_sequence('public.odontologo', 'id_odontologo'),
    GREATEST(COALESCE((SELECT MAX(id_odontologo) FROM public.odontologo), 0), 1),
    COALESCE((SELECT MAX(id_odontologo) FROM public.odontologo), 0) > 0
);

SELECT setval(
    pg_get_serial_sequence('public.consultorio', 'id_consultorio'),
    GREATEST(COALESCE((SELECT MAX(id_consultorio) FROM public.consultorio), 0), 1),
    COALESCE((SELECT MAX(id_consultorio) FROM public.consultorio), 0) > 0
);

SELECT setval(
    pg_get_serial_sequence('public.cita', 'id_cita'),
    GREATEST(COALESCE((SELECT MAX(id_cita) FROM public.cita), 0), 1),
    COALESCE((SELECT MAX(id_cita) FROM public.cita), 0) > 0
);

SELECT setval(
    pg_get_serial_sequence('public.tratamiento', 'id_tratamiento'),
    GREATEST(COALESCE((SELECT MAX(id_tratamiento) FROM public.tratamiento), 0), 1),
    COALESCE((SELECT MAX(id_tratamiento) FROM public.tratamiento), 0) > 0
);

SELECT setval(
    pg_get_serial_sequence('public.pago', 'id_pago'),
    GREATEST(COALESCE((SELECT MAX(id_pago) FROM public.pago), 0), 1),
    COALESCE((SELECT MAX(id_pago) FROM public.pago), 0) > 0
);

SELECT setval(
    pg_get_serial_sequence('public.factura', 'id_factura'),
    GREATEST(COALESCE((SELECT MAX(id_factura) FROM public.factura), 0), 1),
    COALESCE((SELECT MAX(id_factura) FROM public.factura), 0) > 0
);

SELECT setval(
    pg_get_serial_sequence('public.recordatorio', 'id_recordatorio'),
    GREATEST(COALESCE((SELECT MAX(id_recordatorio) FROM public.recordatorio), 0), 1),
    COALESCE((SELECT MAX(id_recordatorio) FROM public.recordatorio), 0) > 0
);

SELECT setval(
    pg_get_serial_sequence('public.historia_clinica', 'id_historia'),
    GREATEST(COALESCE((SELECT MAX(id_historia) FROM public.historia_clinica), 0), 1),
    COALESCE((SELECT MAX(id_historia) FROM public.historia_clinica), 0) > 0
);

SELECT setval(
    pg_get_serial_sequence('public.historia_clinica_detallada', 'id_historia_detallada'),
    GREATEST(COALESCE((SELECT MAX(id_historia_detallada) FROM public.historia_clinica_detallada), 0), 1),
    COALESCE((SELECT MAX(id_historia_detallada) FROM public.historia_clinica_detallada), 0) > 0
);

SELECT setval(
    pg_get_serial_sequence('public.odontograma', 'id_odontograma'),
    GREATEST(COALESCE((SELECT MAX(id_odontograma) FROM public.odontograma), 0), 1),
    COALESCE((SELECT MAX(id_odontograma) FROM public.odontograma), 0) > 0
);

SELECT setval(
    pg_get_serial_sequence('public.proveedor', 'id'),
    GREATEST(COALESCE((SELECT MAX(id) FROM public.proveedor), 0), 1),
    COALESCE((SELECT MAX(id) FROM public.proveedor), 0) > 0
);

SELECT setval(
    pg_get_serial_sequence('public.rol', 'id'),
    GREATEST(COALESCE((SELECT MAX(id) FROM public.rol), 0), 1),
    COALESCE((SELECT MAX(id) FROM public.rol), 0) > 0
);

SELECT setval(
    pg_get_serial_sequence('public.servicio', 'id'),
    GREATEST(COALESCE((SELECT MAX(id) FROM public.servicio), 0), 1),
    COALESCE((SELECT MAX(id) FROM public.servicio), 0) > 0
);

SELECT setval(
    pg_get_serial_sequence('public.password_reset_token', 'id_token'),
    GREATEST(COALESCE((SELECT MAX(id_token) FROM public.password_reset_token), 0), 1),
    COALESCE((SELECT MAX(id_token) FROM public.password_reset_token), 0) > 0
);

COMMIT;
